// Globalflag-coverage prints a matrix of persistent global flag usage per cobra command.
//
// Usage (from repo root):
//
//	go run ./cmd/globalflag-coverage
//	go run ./cmd/globalflag-coverage -markdown > docs/generated/GLOBAL_FLAG_COVERAGE.md
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/NikashPrakash/dot-agents/internal/globalflagcov"
)

func main() {
	markdown := flag.Bool("markdown", false, "emit GitHub-flavored markdown table")
	outPath := flag.String("o", "", "write output to this file instead of stdout")
	flag.Parse()

	wd, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(os.Stderr, "getwd: %v\n", err)
		os.Exit(1)
	}
	modRoot := findModuleRoot(wd)
	if modRoot == "" {
		fmt.Fprintf(os.Stderr, "could not find module root from %s\n", wd)
		os.Exit(1)
	}

	rows, err := globalflagcov.Report(modRoot)
	if err != nil {
		fmt.Fprintf(os.Stderr, "report: %v\n", err)
		os.Exit(1)
	}

	var b strings.Builder
	if *markdown {
		writeMarkdown(&b, rows)
	} else {
		writeTSV(&b, rows)
	}

	if *outPath != "" {
		if err := os.WriteFile(*outPath, []byte(b.String()), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "write %s: %v\n", *outPath, err)
			os.Exit(1)
		}
		return
	}
	fmt.Print(b.String())
}

func findModuleRoot(start string) string {
	dir := start
	for i := 0; i < 64; i++ {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	return ""
}

func writeTSV(b *strings.Builder, rows []globalflagcov.Row) {
	b.WriteString("command_path\tjson\tdry_run\tyes\tforce\tverbose\thandler\tnotes\n")
	for _, r := range rows {
		fmt.Fprintf(b, "%s\t%v\t%v\t%v\t%v\t%v\t%s\t%s\n",
			r.Path, r.Flags.JSON, r.Flags.DryRun, r.Flags.Yes, r.Flags.Force, r.Flags.Verbose, r.Handler, r.Notes)
	}
}

func writeMarkdown(b *strings.Builder, rows []globalflagcov.Row) {
	b.WriteString("<!-- Generated by: go run ./cmd/globalflag-coverage -markdown -o docs/generated/GLOBAL_FLAG_COVERAGE.md -->\n\n")
	b.WriteString("## Global persistent flag coverage\n\n")
	b.WriteString("Each row is one `dot-agents` subcommand path. A cell is **yes** if `commands.Flags.<field>` is read transitively from that command's `Run`/`RunE` handler (same-package callees only).\n\n")
	b.WriteString("| Command | `--json` | `--dry-run` | `--yes` | `--force` | `--verbose` | Handler | Notes |\n")
	b.WriteString("|---------|:---:|:---:|:---:|:---:|:---:|---------|-------|\n")
	for _, r := range rows {
		fmt.Fprintf(b, "| `%s` | %s | %s | %s | %s | %s | `%s` | %s |\n",
			r.Path,
			yn(r.Flags.JSON), yn(r.Flags.DryRun), yn(r.Flags.Yes), yn(r.Flags.Force), yn(r.Flags.Verbose),
			r.Handler, escMD(r.Notes))
	}
}

func yn(v bool) string {
	if v {
		return "yes"
	}
	return "no"
}

func escMD(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	if s == "" {
		return "—"
	}
	return s
}
